/*
 =========================================================================================
 Name        : Ultrasonic.h
 Author      : Mohamed Ashraf El-Sayed
 Version     : 1.0.0
 Copyright   : Your copyright notice
 date        : Tue, Oct 17 2023
 time        :
 Description : ULTRASONIC Driver Header file , Ansi-style
 =========================================================================================
*/

#ifndef _ULTRASONIC_H_
#define _ULTRASONIC_H_
/* ----------------------------------------------------------------------------------- */
/* ------------------Includes section------------------- */
#include "gpio.h"
#include "timer1.h"


/* ----------------------------------------------------------------------------------- */
/* -----user_defined data type declaration section------ */
#if TIMER1_MODE_SELECT == TIMER1_MODE_OVER_FLOW
/* Ultrasonic config structure */
typedef struct{
	/* pointer to function to hold the function called in the APPLICATION layer */
	void (* ULTRASONIC_DefaultHandler)(void);
	/* holds the configurations of the ICU */
	timer1_overflow_config_t icu_cfg;
}ultrasonic_config_t;
#endif


/* ----------------------------------------------------------------------------------- */
/* -------------------Global section-------------------- */
#if TIMER1_MODE_SELECT == TIMER1_MODE_OVER_FLOW
/* Ultrasonic Trigger pin Object declaration to be initialized in the APPLICATION Layer */
extern gpio_config_t Ultrasonic_TriggerPin;
#endif


/* ----------------------------------------------------------------------------------- */
/* ------------functions declaration section------------ */


#if TIMER1_MODE_SELECT == TIMER1_MODE_OVER_FLOW
/**
 * @brief  initialize the Ultrasonic :
 * 				1- Initialize the ICU Driver
 * 				2- Setup the ICU Call Back function
 * 				3- Setup the direction of the Trigger pin as Output through the GPIO Driver
 * @param  (ultrasonic_obj)  pointer to the Ultrasonic object passed by reference
 * @return (l_status) 	     status of the performed operation
 *              (E_NOT_OK)  	operation failed
 *              (E_OK)      	operation success
 */
Std_ReturnType Ultrasonic_init(ultrasonic_config_t *ultrasonic_obj);


/**
 * @brief  Send the Trigger pulse to the Ultrasonic
 */
void Ultrasonic_Trigger(void);


/**
 * @brief  	- Send the Trigger pulse using Ultrasonic_Trigger function
 * 			- Start the measurements by the ICU from this moment
 * @param  (counts) holds the number of ticks of Timer/Counter1 during the high pulse of the echo pin captured by ICU
 * @return the returned distance in Centimeter
 */
uint16 Ultrasonic_readDistance(uint16 counts);


/**
 * @brief  	- this is the call back function called by the ICU Driver
 * 			- this is used to calculate the high time (pulse time) generated by the Ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void);
#endif


/* ----------------------------------------------------------------------------------- */
#endif /* _ULTRASONIC_H_ */
